export enum OrderStatus {
    AWAITING_PAYMENT = 'AWAITING_PAYMENT',
    AWAITING_SHIPMENET = 'AWAITING_SHIPMENT',
    SHIPPED = 'SHIPPED',
    IN_TRANSIT = 'IN_TRANSIT',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
}